class OutfitGenerator {
    constructor(strategies) {
        this.strategies = strategies;
    }

    async generateOutfit(userId, options) {
        // Create an array to hold the outfits generated by each strategy
        let outfits = [];
        console.log('came to outfit generator');
        console.log('strategies:', this.strategies);

        // Use each strategy to generate an outfit
        for (let strategy of this.strategies) {
            let outfit = await strategy.generateOutfit(userId, options);
            outfits.push(outfit);
        }

        // Return the array of outfits
        return outfits;
    }
}

module.exports = OutfitGenerator;