
module.exports = {
    colorOptions: ['Red', 'Blue', 'Green', 'Yellow', 'Black', 'White', 'Gray', 'Brown', 'Pink','Purple','Orange','Beige'],
    styleOptions: ['Casual', 'Formal', 'Sportswear', 'Evening'],
    categoryOptions: ['Top', 'Bottom', 'Shoes', 'One-piece', 'Outerwear'],
    subCategoriesofTop: ['T-shirt', 'Blouse', 'Sweater','Shirt'],
    subCategoriesofBottom: ['Pants', 'Shorts', 'Jeans', 'Skirt','Leggings'],
    subCategoriesofShoes: ['Sneakers', 'Sandal', 'Boots','Flats','Heels'],
    subCategoriesofOnePiece: ['Dress', 'Jumpsuit'],
    subCategoriesofOuterwear: ['Jacket', 'Coat'],
    weatherOptions: ['Hot', 'Cold','Cool','Warm'],
    patternOptions: ['Solid', 'Striped', 'Polka-dot', 'Floral', 'Checkered'],
    DetailsTop: [ 'fit_type', 'sleeveLength'],
    detailsBottom: ['bottomLength', 'waistType','fit_type'],
    detailsOnePiece:['fit_type', 'sleeveLength', 'bottomLength'],
    detailsOuterwear:['fit_type', 'sleeveLength'],
    detailsShoes:['Fabric'],
    fitType: ['Oversize', 'Slim', 'Regular',],
    sleeveLength: ['Sleeveless','Short', 'Long'],
    bottomLength: ['Short', 'Midi', 'Maxi'],
    waistType:  ['High-rise', 'Low-rise', 'Normal'],
    timeOptions: ['Morning', 'Afternoon', 'Evening'],
    fabricOptions: ['Textile','Leather','Suede','Canvas'],
};